# Generated by Django 2.2.12 on 2020-04-20 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除标记')),
                ('project_name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('manager', models.CharField(max_length=100, verbose_name='项目经理')),
            ],
            options={
                'verbose_name_plural': '项目表',
                'db_table': 'tms_project',
                'verbose_name': '项目表',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除标记')),
                ('case_no', models.CharField(max_length=50, verbose_name='用例编号')),
                ('project_model', models.CharField(max_length=100, verbose_name='所属模块')),
                ('project_desired', models.TextField(verbose_name='相关需求')),
                ('case_title', models.CharField(max_length=200, verbose_name='用例标题')),
                ('pre_condition', models.CharField(max_length=200, verbose_name='前置条件')),
                ('expect_result', models.TextField(verbose_name='预期结果')),
                ('expect_reality', models.TextField(verbose_name='实际结果')),
                ('level', models.SmallIntegerField(choices=[(0, '高'), (1, '中'), (2, '低')], default=1, verbose_name='优先级')),
                ('case_type', models.SmallIntegerField(choices=[(0, '功能型'), (1, '页面校验')], default=0, verbose_name='用例类型')),
                ('create_by', models.CharField(max_length=100, verbose_name='用例创建者')),
                ('judge_by', models.CharField(max_length=100, verbose_name='用例评审者')),
                ('judge_result', models.SmallIntegerField(choices=[(0, '通过'), (1, '不通过'), (2, '未审核'), (3, '作废')], default=2, verbose_name='评审结果')),
                ('case_statu', models.SmallIntegerField(choices=[(0, '未执行'), (1, '已执行'), (2, '弃用')], default=0, verbose_name='用例状态')),
                ('case_result', models.SmallIntegerField(choices=[(0, '通过'), (1, '未通过'), (2, '弃用')], default=0, verbose_name='用例执行结果')),
                ('remark', models.CharField(max_length=200, verbose_name='备注')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name_plural': '用例表',
                'db_table': 'tms_case',
                'verbose_name': '用例表',
            },
        ),
    ]
