# Generated by Django 2.2.12 on 2020-04-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='run_step',
            field=models.CharField(default='', max_length=300, verbose_name='执行步骤'),
            preserve_default=False,
        ),
    ]
